/* 컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴
   Copyright 1991-1997 Sierra On-Line.  All Rights Reserved.

   This code is copyrighted and intended as an aid in writing utilities
   for the Front Page Sports Football products.  All rights reserved.

   THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF 
   ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO 
   THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A 
   PARTICULAR PURPOSE.
컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴컴 */

#ifndef APTCOUNT_H
#define APTCOUNT_H

#define QB_COUNT 2
#define FB_COUNT 2
#define HB_COUNT 1
#define TE_COUNT 2
#define WR_COUNT 3
#define  C_COUNT 2
#define  G_COUNT 3
#define  T_COUNT 1
#define DE_COUNT 4
#define DT_COUNT 0
#define LB_COUNT 5
#define CB_COUNT 4
#define  S_COUNT 3
#define  K_COUNT 1
#define  P_COUNT 1
#define APT_COUNT 34

#endif   // APTCOUNT_H


/*
QB_COUNT,FB_COUNT,HB_COUNT,TE_COUNT,WR_COUNT,C_COUNT,G_COUNT,T_COUNT,DE_COUNT,DT_COUNT,LB_COUNT,CB_COUNT,S_COUNT,K_COUNT,P_COUNT
*/
